name: Secrets
on: 
  workflow_dispatch

jobs:
  secret-repo:
    runs-on: ubuntu-latest
    env:
      EMAIL_API_KEY: ${{ secrets.EMAIL_KEY }}

    steps:
      - name: Read secret
        run: echo "Secret value ${{ secrets.EMAIL_KEY }}"
        
      - name: Read env
        run: echo "Env value $EMAIL_API_KEY"
  
  secret-production:
    runs-on: ubuntu-latest
    environment: github-pages
    env: 
      EMAIL_API_KEY: ${{ secrets.EMAIL_KEY }}

    steps:        
      - name: Read
        run: echo "Env value $EMAIL_API_KEY"
